### ISSUE TITLE
unable to connect to jupyter notebook (Can't access http://localhost:8123)

### ISSUE THREAD

**Issue by dat4git** [Nealelab/cloudtools#128]
I'm running into the following issue when trying to connect to the notebook. The cluster instance is successfully created but when I try to launch the notebook I get a "can't access http://localhost:8123" page and the errors listed below in the terminal. We had previously observed this issue with the dev version of Chrome but I'm currently using the official build (Version 72.0.3626.81) and was wondering if anyone has run into this problem with this version?

(py36) wm8cd-7e5:ESC ghoshs$ cluster connect test notebook
Connecting to cluster 'test'...
Warning: Permanently added 'compute.2461785027591511535' (ECDSA) to the list of known hosts.
(py36) wm8cd-7e5:ESC ghoshs$ channel 15: open failed: administratively prohibited: open failed
channel 16: open failed: administratively prohibited: open failed
channel 17: open failed: administratively prohibited: open failed

**Comment by danking** [comment]
Google broke proxying to localhost in version 72:

https://chromium.googlesource.com/chromium/src/+/da790f920bbc169a6805a4fb83b4c2ab09532d91

This appears to be an intentional break. We can fix by adding a parameter to chrome startup: `--proxy-bypass-list=<-loopback>`
