### ISSUE TITLE
standard zone us-central1-f

### ISSUE THREAD

**Issue by andgan** [Nealelab/cloudtools#19]
we received an email from google suggesting to use us-central1-f. I suggest to use this as the default zone in the `start-cluster` script

**Comment by andgan** [comment]
We received an email from google, but might be only for our projects, will ask.
Cheers,

**Comment by howrigan** [comment]
What is the command option to change the region in these scripts?

**Comment by liameabbott** [comment]
`cluster name start --zone us-central1-f` would start a cluster in zone us-central1-f
