### ISSUE TITLE
Request: provide option to pass through arguments for job submission

### ISSUE THREAD

**Issue by rkwalters** [Nealelab/cloudtools#25]
In `cluster submit`, it would be helpful to have a way to pass through arguments to the job script. 

Syntax for this in `gcloud beta dataproc jobs submit spark` is an empty `--` argument followed by the arguments for the job script. This is appended after all of the existing arguments for `gcloud` setup. 

Not sure how best to expose this on the command line for `cluster submit` though. As a named argument taking a quoted string? Taking all leftovers from `argparse.parse_known_args()`?

**Comment by liameabbott** [comment]
Addressed with #27, PyPI version 1.1.2. 

I've added the functionality to pass a quoted string containing arguments for the submitted Hail script to submit's `--args`.

For example, submitting with
```
cluster submit mycluster myhailscript.py --args "arg1 arg2"
```
would give you access to `sys.argv[1] = 'arg1'` and `sys.argv[2] = 'arg2'` in `myhailscript.py`.
