### ISSUE TITLE
Installing initialization packages

### ISSUE THREAD

**Issue by davek44** [Nealelab/cloudtools#28]
Hi all,

Very much appreciate your effort here!

In the article [Using Hail on the Google Cloud Platform](http://discuss.hail.is/t/using-hail-on-the-google-cloud-platform/80), you suggest that I can install additional initialization packages by writing a script similar to your own gs://hail-common/hail-init.sh and providing it in a comma-separated list. Now that I'm using cloudtools, I similarly offer my script with yours via the --init option.

I've tried doing that where I'd very much like to install the python package "google-cloud-storage" so that I can interact with files in buckets through that API. However, I've had no luck with this method; my scripts cannot import google-cloud-storage.

However, I stumbled upon a strategy that does work. If I start the cluster, connect via a notebook, and open a Hail notebook, I can run pip to install the package. After that, when I run cluster submit to send full scripts, they acknowledge presence of the package and run well.

Any idea what's going on here, and whether I can cut out the notebook step to initialize with google-cloud storage and other future packages I might like to install? Thanks!

Best,
Dave

**Comment by liameabbott** [comment]
Hi Dave,

I think this issue stems from us installing an Anaconda distribution of Python by default in the notebook initialization script and using that to run the notebooks. When you pip install a package from the notebook, it uses the Anaconda distribution's pip, but I'm guessing when you were using pip install in your own init script, it was using a different pip and in the notebooks the Anaconda Python couldn't see that installation of the package. 

Regardless, I've moved away from using Anaconda by default in #31 and instead using the default system Python. I've also added a `--pkgs` flag to the `cluster start`. You should be able to specify packages to install with pip either using that flag, i.e. `cluster start mycluster --pkgs pandas,google-cloud-storage`, or by pip installing from your own init script supplied with `--init`.

Thanks,
Liam

**Comment by tpoterba** [comment]
We also have some utility functions in Hail that let you interact with hadoop-connected file systems (like buckets): https://hail.is/docs/stable/utils/index.html 

They're probably not as fast as the standalone Python library (they use the same socket as the other py4j communication) but may be worth using for simplicity.

**Comment by davek44** [comment]
That worked well. Thanks!
