### ISSUE TITLE
Add --max-idle flag option to start.py

### ISSUE THREAD

**Issue by gtiao** [Nealelab/cloudtools#55]
Hi, team

I've been manually editing my start.py script every time I update cloudtools so that the script takes in an additional optional parameter and the call reads

`gcloud beta <normal_pars> --max-idle <default_par>`

so that I can take advantage of the `max-idle` option in gcloud beta. A very large number of people in the MacArthur Lab also would like to take advantage of `max-idle`, so I've been distributing my copy of the start script, but it would be nice to have this as part of the official cloudtools distribution.

Thanks!

Grace

**Comment by rkwalters** [comment]
Would it be worth more broadly having any non-cloudtools arguments get passed through to gcloud? E.g. `--tags` and `--project` are both potentially handy. Should be possible with `argparse.parse_known_args()`.

**Comment by gtiao** [comment]
I think that's a great suggestion -- but note that for `--max-idle` it's
not only just an additional argument that has to be passed but the `gcloud`
command that has to be altered (to `gcloud beta`, as the `--max-idle`
feature isn't recognized by regular `gcloud`).



Grace Tiao
Computational Biologist

MacArthur Lab
The Broad Institute
75 Ames St.
Room 10022-D
Cambridge, MA 02142
Tel: (617) 714-8523
