### ISSUE TITLE
Default args seem to load wrong Hail version

### ISSUE THREAD

**Issue by cwhelan** [Nealelab/cloudtools#70]
The documentation says that 'devel' is the default Hail version, but if I run

```cluster start cw-hail -p 6```

And then try to execute this script:

```
import hail as hl
hl.init()
```

I get the error:

```AttributeError: 'module' object has no attribute 'init'```

A script like this runs successfully though, so I think it's loading Hail 0.1 instead of 'devel':

```
from hail import *

hc = HailContext()
```

My Hail devel version script runs successfully if I create the cluster specifying the version and Spark version:

```cluster start cw-hail -p 6 --version devel --spark 2.2.0```

**Comment by jbloom22** [comment]
Do you have the latest version?
`pip install cloudtools --upgrade`

**Comment by cwhelan** [comment]
Yes, I just installed this yesterday, and I get:

`Requirement already up-to-date: cloudtools in /Library/Python/2.7/site-packages (1.1.12)`

**Comment by danking** [comment]
@cwhelan is this still an issue for you? I don't believe this is replicable with latest cloud tools.

**Comment by cwhelan** [comment]
`pip install cloudtools --upgrade` just brought me version 1.2.0 of cloudtools and the problem seems to be fixed in that version.
